config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  get 'question', to: 'pages#question'
  get 'answer', to: 'pages#answer'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def question
  end

  def answer
    if params[:answer] == 'I am going to work'
    @answer = 'Great!'
    end
    if params[:answer] == 'I am going to work?'
      @answer = 'Silly question, get dressed and go to work!'
    end
    if params[:answer] == ''
      @answer = 'I dont care, get dressed and go to work!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="stylesheet" href="style.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/answer.html.erb
<nav class="navbar" style="background-color: #157347;">
  <div class="text-light text-start fs-5 fw-medium ">
      <img src="https://images.ctfassets.net/xz1dnu24egyd/3uj0WByKthyDWCOhCFTQIw/abf94946627aa6b5fc483149a56ba942/gitlab-logo-700.png" class=fa-beat-fade width="45" height="40">Answer
  </div>
</nav>

<br><ul><%= @answer %></ul>
<ul><%= link_to "home", root_path, class:"btn btn-dark" %>
  <%= link_to "Question", question_path, class:"btn btn-primary" %></ul>

app/views/pages/home.html.erb
<nav class="navbar" style="background-color: #000000;">
  <div class="text-light text-start fs-5 fw-medium ">
      <img src="https://images.ctfassets.net/xz1dnu24egyd/3uj0WByKthyDWCOhCFTQIw/abf94946627aa6b5fc483149a56ba942/gitlab-logo-700.png" class=fa-flip width="45" height="40">Home page
  </div>
</nav>
<br>
 <ul><%= link_to "Question", question_path, class:"btn btn-primary" %>
  <%= link_to "Answer", answer_path, class:"btn btn-success" %></ul>

app/views/pages/question.html.erb
<nav class="navbar" style="background-color: #0d6efd;">
  <div class="text-light text-start fs-5 fw-medium ">
      <img src="https://images.ctfassets.net/xz1dnu24egyd/3uj0WByKthyDWCOhCFTQIw/abf94946627aa6b5fc483149a56ba942/gitlab-logo-700.png" class=fa-spin width="45" height="40">Question
  </div>
</nav>
<br>
<ul><form action="/answer" data-turbo="false">
  <input type="text" name="answer">
  <input type="submit" value="Ask!">
</form></ul>

<br>
<ul><%= link_to "home", root_path, class:"btn btn-dark" %>
<%= link_to "Answer", answer_path, class:"btn btn-success" %></ul>